using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ChallangeMoveChara : MonoBehaviour
{
    //=====å¤‰æ•°å®£è¨€éƒ¨=======================================================================
    private const string key_isWalk = "walk";
    private const string key_isJump = "jump";

    //Rigidbodyç”¨ã®å¤‰æ•°
    private Rigidbody rb;

    //animatorç”¨ã®å¤‰æ•°
    private Animator animator;

    // ï¿½ï¿½]ï¿½Ì‘ï¿½ï¿½xï¿½ğ’²ï¿½
    private float turnSpeed;

    //GmaeManagerã®å®£è¨€
    private ChallengeGameManager gm;

    //æ¢¯å­ã‚’ä¸Šã‚‹ç®¡ç†ã‚’ã—ã¦ã„ã‚‹å¤‰æ•°
    public bool crimeFlag;

    public AudioClip walkSound; // æ­©è¡ŒåŠ¹æœéŸ³ã®AudioSource
    public AudioClip jumpSound; // ã‚¸ãƒ£ãƒ³ãƒ—åŠ¹æœéŸ³ã®AudioSource
    public AudioClip crimeSound; // ã‚¸ãƒ£ãƒ³ãƒ—åŠ¹æœéŸ³ã®AudioSource



    //===ã‚³ã‚³ã‹ã‚‰Start()=====================================================================
    void Start()
    {
        rb = GetComponent<Rigidbody>(); // Rigidbodyã‚³ãƒ³ãƒãƒ¼ãƒãƒ³ãƒˆã®å‚ç…§ã‚’å–å¾—ã—ã¦ä»£å…¥
        gm = FindObjectOfType<ChallengeGameManager>();//GameManagerã®ã‚¤ãƒ³ã‚¹ã‚¿ã‚¹ç”Ÿæˆ
        crimeFlag = false;//æ¢¯å­ã‚’ã®ã¼ã‚‹ãŸã‚ã®å¤‰æ•°
        animator = GetComponent<Animator>();
    }

    // Update is called once per frame
    void Update()
    {
        if (gm.aryCnt >= -1)//GameManegerã®moveCntã®ã‚«ã‚¦ãƒ³ãƒˆãŒï¼ã§ãªã„æ™‚
        {
            if (gm.charaAction == "walk")//ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã®æŒ‡ç¤ºãŒwalkã®æ™‚
            {
                StartCoroutine(Advance());
            }
            else if (gm.charaAction == "jump")//ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã®æŒ‡ç¤ºãŒjumpã®æ™‚
            {
                StartCoroutine(Jump());
            }
            else if (gm.charaAction == "climb")//ã‚­ãƒ£ãƒ©ã‚¯ã‚¿ãƒ¼ã®æŒ‡ç¤ºãŒcrimeã®æ™‚
            {
                if (crimeFlag)
                {
                    StartCoroutine(Up());
                }
            }
        }
    }

    //====ã‚³ãƒ«ãƒ¼ãƒãƒ³é–¢æ•°ã‚’å®šç¾©==============================================================
    public IEnumerator Advance()//ä¸€æ­©é€²ã‚€
    {
        animator.SetBool(key_isWalk, true);
        rb.velocity = new Vector3(3.46f, 0, 0);//Vector3(æ¨ªç§»å‹•, ä¸Šä¸‹ç§»å‹•, å¥¥è¡Œç§»å‹•)
        AudioSource.PlayClipAtPoint(walkSound, transform.position); // æ­©è¡ŒåŠ¹æœéŸ³ã‚’å†ç”Ÿ
        yield return new WaitForSeconds(0.3f);
        animator.SetBool(key_isWalk, false);
    }

    public IEnumerator Jump()// ã‚¸ãƒ£ãƒ³ãƒ—ã™ã‚‹ãŸã‚ã®é–¢æ•°
    {
        animator.SetBool(key_isJump, true);
        yield return new WaitForSeconds(1.5f); // 1.5ç§’å¾…æ©Ÿ
        rb.velocity = new Vector3(1.4f, 6.0f, 0f);//Vector3(æ¨ªç§»å‹•, ä¸Šä¸‹ç§»å‹•, å¥¥è¡Œç§»å‹•
        AudioSource.PlayClipAtPoint(jumpSound, transform.position); // ã‚¸ãƒ£ãƒ³ãƒ—åŠ¹æœéŸ³ã‚’å†ç”Ÿ
        yield return null;//1ãƒ•ãƒ¬ãƒ¼ãƒ å¾…æ©Ÿ
        animator.SetBool(key_isJump, false);
    }

    //Up,OneWalk,TurnBackã¯æ¢¯å­ã‚’ã®ã¼ã‚‹ãŸã‚ã®ã‚³ãƒ«ãƒ¼ãƒãƒ³
    public IEnumerator Up() //æ¢¯å­ã‚’ä¸Šã‚‹
    {
        float t = 0f;
        Quaternion startRotation = transform.rotation;
        Quaternion endRotation = Quaternion.Euler(0, 0f, 0);//å›è»¢ç”¨
        //æ¢¯å­æ–¹å‘ã¸å‘ãã‚’å¤‰æ›´
        while (t < 1.0f)
        {
            t += Time.deltaTime * 2.0f;
            transform.rotation = Quaternion.Lerp(startRotation, endRotation, t);
            yield return null;
        }

        rb.velocity = new Vector3(0f, 0f, 3.0f);//æ¢¯å­æ–¹å‘ã«ç§»å‹•
        yield return new WaitForSeconds(1.0f); // 1.5ç§’å¾…æ©Ÿ
        rb.velocity = new Vector3(0, 5.0f, 0);//ä¸Šæ˜‡ã®è¨˜è¿°
        AudioSource.PlayClipAtPoint(crimeSound, transform.position); // ã‚¸ãƒ£ãƒ³ãƒ—åŠ¹æœéŸ³ã‚’å†ç”Ÿ
        rb.useGravity = false;//é‡åŠ›ã®ç„¡åŠ¹åŒ–
        yield return null;
    }

    public IEnumerator OneWalk()// ã‚¹ãƒ†ãƒ¼ã‚¸ã¸ä¸ŠãŒã‚‹
    {
        rb.velocity = new Vector3(0f, 0f, -3.0f);
        yield return null;
    }


    public IEnumerator TurnBack()//é€²è¡Œæ–¹å‘ã«å‘ãã‚’å¤‰ãˆã‚‹
    {
        float t = 0f;
        Quaternion startRotation = transform.rotation;
        Quaternion endRotation = Quaternion.Euler(0, 90f, 0);//é€²è¡Œæ–¹å‘ã®å‘ãã¸
        while (t < 1f)
        {
            t += Time.deltaTime * 1.0f;
            transform.rotation = Quaternion.Lerp(startRotation, endRotation, t);
            yield return null;
        }
        yield return new WaitForSeconds(2.0f); // 1.5ç§’å¾…æ©Ÿ
    }

    //====ä»¥ä¸‹é–¢æ•°============================================================================
    private void OnTriggerEnter(Collider other)
    {
        //æ¢¯å­ã‚’ä¸Šã‚‹ã‹ã®åˆ¤æ–­
        if (other.gameObject.tag == "crime" && !crimeFlag)
        {
            crimeFlag = true;
        }
        else if (other.gameObject.tag == "crimeEnd" && crimeFlag)
        {
            StartCoroutine(TurnBack());
            StartCoroutine(OneWalk());
            crimeFlag = false;
            rb.useGravity = true;
        }
        else if (other.gameObject.tag == "crimeCancel" && crimeFlag)
        {
            crimeFlag = false;
        }

        //ã‚¹ãƒ†ãƒ¼ã‚¸å¤–ãªã©ã«è¡Œã£ãŸã¨ãã®å‡¦ç†
        if (other.gameObject.tag == "gameOver")
        {
            gm.gameOverFlag = true;
        }
    }

    private void OnCollisionEnter(Collision collision)
    {
        if (collision.gameObject.tag == "boxShow")
        {
            gm.boxShow = "show";
        }
    }
}
